config/routes.rb
Rails.application.routes.draw do

  get 'reservations/new'

  devise_for  :members, 
              :path => '',
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'},
              :controllers => { :registrations => 'registrations', 
                                :omniauth_callbacks => "omniauth_callbacks" }

  
  root 'home#index'

  resources :members, only: [:edit, :update] do
    resource :profile, only: [:edit, :update, :destroy] do
      collection do
        patch 'upload_avatar'
      end
    end
  end

  resources :members do
    get :payout_account, on: :member
  end
  
  resource :member, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'profile', to: 'profiles#edit'
  get 'host_locations', to: 'members#member_locations'

  resources :locations do
    member do
      get :add_images
      get :calendar
      get :add_available_dates
    end
  end

  resources :reservations, only: [:new, :create, :index] do
    get :confirmation, on: :member
  end

end

app/views/shared/_avatar-form.html.erb
<%= form_for([@member, @profile], url: upload_avatar_member_profile_path(@member), id: "avatar-form", html: { multipart: true, method: "patch" }) do |f| %>

  <%= f.hidden_field :member_id %>
  <%= f.file_field :avatar %>
  <%= f.submit "Upload", class: "btn btn-primary btn-upload" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center">
  <div class="container">
    <div class="row">
      <h6>MusicaB&B <%= Time.now.year %></h6>
    </div>
  </div>
</footer>

app/views/shared/_main_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MusicaB&B</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if member_signed_in? %>  
        <li class="dropdown" role="sign in">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_member.name %>     
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to("Profile", profile_path) %></li>
            <li><%= link_to("Your Locations", host_locations_path) %></li>
            <li><%= link_to("Log Out", destroy_member_session_path, :method => :delete) %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to("Log In", new_member_session_path) %></li>
        <li><%= link_to("Sign Up", new_member_registration_path) %></li>
        <% end %>
        <li><%= link_to "List My Property", new_location_path, class: "btn btn-warning btn-property" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_third-party-login-links.html.erb
<div class="signup-or-separator"> 
  <span> OR </span>
  <hr>
</div>

<% if devise_mapping.omniauthable? %>
  <!-- Link to authenticate with Google -->
  <%= link_to "#{action_text} with Google", member_google_oauth2_omniauth_authorize_path, class: "btn btn-danger google-auth-link" %>
<% end %>