config/routes.rb
Rails.application.routes.draw do

  get 'reservations/new'

  devise_for  :members, 
              :path => '',
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'},
              :controllers => { :registrations => 'registrations', 
                                :omniauth_callbacks => "omniauth_callbacks" }

  
  root 'home#index'

  resources :members, only: [:edit, :update] do
    resource :profile, only: [:edit, :update, :destroy] do
      collection do
        patch 'upload_avatar'
      end
    end
  end

  resources :members do
    get :payout_account, on: :member
  end
  
  resource :member, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'profile', to: 'profiles#edit'
  get 'host_locations', to: 'members#member_locations'

  resources :locations do
    member do
      get :add_images
      get :calendar
      get :add_available_dates
    end
  end

  resources :reservations, only: [:new, :create, :index] do
    get :confirmation, on: :member
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.includes(:location_images, :member).last(3)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<section class="hero">
  <div class="jumbotron search-widget">
    <h3>Book your perfect musical vacation</h3>
    <%= form_tag locations_path, method: :get, class: "form-inline" do %>
      <div class="form-group">
        <%= text_field_tag(:address, nil, class: "form-control", placeholder: "where to? city, state, address") %>
      </div>
      <div class="form-group">
        <%= text_field_tag(:start_date, nil, id: "datepicker-start", class: "form-control", placeholder: "check in") %>
      </div>
      <div class="form-group">
        <%= text_field_tag(:end_date, nil, id: "datepicker-end", class: "form-control", placeholder: "check out") %>
      </div>
      <%= submit_tag "Find Properties", name: "commit", class: "btn btn-primary" %>
    <% end %>
  </div>
</section>

<section class="three-points">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 point">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-music"></i></div>
          <div class="col-xs-9"><p>Our homes include the musical instrument that you can't take with you.</p></div>
        </div>
      </div>
      <div class="col-sm-4 point">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-volume-up"></i></div>
          <div class="col-xs-9"><p>Old or young can share and play whatever they love so much.</p></div>
        </div>  
      </div>
      <div class="col-sm-4 point">
        <div class="row">
          <div class="col-xs-3"><i class="fa fa-compass"></i></div>
          <div class="col-xs-9"><span>You'll love exploring new neighborhoods with joy & laught.</span></div>
        </div>
      </div>
    </div>
  </div>  
</section>

<section class="promo">
  <div class="container">
    <h2 class="text-center">Explore With Us</h2>
    <div class="row">
      
      <% @locations.each do |location| %>
        <div class="col-md-4">
          <div class="panel panel-default panel-1">
            <% unless location.location_images.empty? %>
              <%= link_to location_path(location.id), alt: location.title do %>
                <div class="panel-heading" style="background-image: url(<%= image_url location.location_images[0].picture.url(:square) %>)">
                  <span class="price-label"><%= number_to_currency(location.night_rate, unit: '€', precision: 0) %></span>
                </div>
              <% end %>
            <% end %>
            <div class="panel-body">
              <%= image_tag(location.member.profile.avatar.url(:square), alt: "profile picture", class: "panel-profile-img img-circle pull-right") %>
              <h5 class="panel-title"><%= link_to location.title, location_path(location.id) %></h5>
              <p><%= location.description %></p>
            </div>
          </div>
        </div>    
      <% end %>

    </div>
  </div>
</section>