config/routes.rb
Rails.application.routes.draw do

  get 'reservations/new'

  devise_for  :members, 
              :path => '',
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'},
              :controllers => { :registrations => 'registrations', 
                                :omniauth_callbacks => "omniauth_callbacks" }

  
  root 'home#index'

  resources :members, only: [:edit, :update] do
    resource :profile, only: [:edit, :update, :destroy] do
      collection do
        patch 'upload_avatar'
      end
    end
  end

  resources :members do
    get :payout_account, on: :member
  end
  
  resource :member, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'profile', to: 'profiles#edit'
  get 'host_locations', to: 'members#member_locations'

  resources :locations do
    member do
      get :add_images
      get :calendar
      get :add_available_dates
    end
  end

  resources :reservations, only: [:new, :create, :index] do
    get :confirmation, on: :member
  end

end

app/models/location.rb
class Location < ApplicationRecord
  paginates_per 10

  belongs_to :member

  has_many :location_images, dependent: :destroy
  accepts_nested_attributes_for :location_images, allow_destroy: true

  has_many :reservations, dependent: :destroy
  has_many :available_dates, dependent: :destroy

  validates_presence_of :title, 
                        :description, 
                        :address_1, 
                        :city,
                        :state,
                        :musical_instrument,
                        :night_rate,
                        :guests,  
                        :member_id

  geocoded_by :full_street_address

  after_validation :geocode, if: ->(obj){ obj.address_1.present? and obj.address_changed? }
  after_validation :lat_changed?

  after_initialize :set_default_status

  scope :nearby, ->(address) { near(address, 50) if address.present? }
  scope :with_available_dates, ->(date_range_array) {
    joins(:available_dates)
    .merge(AvailableDate.available_for_reservation(date_range_array)) if date_range_array.present?
  }
  scope :with_musical_instrument, ->(instrument) { where(musical_instrument: instrument) if instrument.present? }
  scope :with_guests, ->(no_of_guests) { where(guests: no_of_guests) if no_of_guests.present? }

  def full_street_address
    [address_1, city, state].compact.join(", ")
  end

  def address_changed?
    address_1_changed? || city_changed? || state_changed?
  end

  # This is used to make sure that our address is actually parsed 
  # properly and we get a valuable lat/long
  def lat_changed?
    if (self.address_changed?)
      if !(self.latitude_changed?)
        self.errors.add(:address, "is not valid")
        return false
      end
    end
    return true
  end

  def create_available_dates(start_date, end_date)
    dates = start_date.to_datetime.upto(end_date.to_datetime)
    dates.each do |date|
      AvailableDate.find_or_create_by(date: date, location_id: self.id, booked: false)
    end
  end

  def future_available_dates
   future_dates = AvailableDate.where("date >= ?", Date.today)
   future_dates.where(booked: false)
   #or
   #future_dates.where(reservation_id: nil)
  end

  def set_default_status
    self.status = "draft" if self.new_record?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_member!, only: [:new, :edit, :create, :update, :destroy, :add_images, :calendar, :add_available_dates]
  before_action :set_location, only: [:show, :edit, :update, :destroy, :add_images, :calendar, :add_available_dates]

  # GET /locations
  # GET /locations.json
  def index
    if params[:start_date].present? || params[:end_date].present? || params[:address].present? || params[:musical_instrument].present? || params[:guests].present?
      @locations = SearchForLocationService.new({
        start_date: params[:start_date],
        end_date: params[:end_date],
        address: params[:address],
        musical_instrument: params[:musical_instrument],
        guests: params[:guests]
      }).matches.includes(:location_images, :member).page(params[:page]).per(10)
    else
      @locations = Location.all.includes(:location_images, :member).page(params[:page]).per(10)
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
     @available_dates = @location.available_dates.where(booked: false).pluck(:date).as_json
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
    authorize @location
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)
    respond_to do |format|
      if @location.save
        #byebug
        format.html { redirect_to add_images_location_path(@location), notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    authorize @location
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    authorize @location
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_images   
  end

  def calendar
    authorize @location
  end

  def add_available_dates
    @location.create_available_dates(params[:start_date], params[:end_date])
    redirect_to calendar_location_path(@location), notice: "Successfully added available dates"
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:title, :description, :address_1, :address_2, :city, 
        :state, :postcode, :musical_instrument, :night_rate, :guests, :member_id,
        location_images_attributes: [:id, :picture, :picture_order, :_destroy, :location_id])
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(location, html: { class: "form-horizontal" }) do |f| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>
  </div>


  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control", placeholder: "Description of your location" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address_1, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address_1, class: "form-control", placeholder: "Address 1" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address_2, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address_2, class: "form-control", placeholder: "Address 2" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control", placeholder: "City" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control", placeholder: "State" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :postcode, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :postcode, class: "form-control", placeholder: "Postcode" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :musical_instrument, "Musical Instrument", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :musical_instrument, class: "form-control", placeholder: "Musical Instrument" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :night_rate, "Night Rate", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :night_rate, class: "form-control", placeholder: "Night Rate in Euro" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :guests, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :guests, class: "form-control", placeholder: "Number of Guests" %>
    </div>
  </div>

  <%= f.hidden_field :member_id, value: current_member.id %>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/locations/add_images.html.erb
<div class="container">
  <div class="dropzone-wrapper">
    <h2 class="main-title">Add Pictures</h2>
   
    <%= form_for @location, html: { multipart: true, class: "dropzone dz-clickable", id: "dropzone"}  do |f| %>
      <%= f.fields_for :location_images, LocationImage.new do |image| %>
        <div class="dz-message" data-dz-message><span>Drop files here or click to upload.</span></div>
        <div class="fallback">  
          <%= image.file_field :picture %>
          <%= f.submit "UPDATE & SAVE" %>     
        </div>    
      <% end %>
    <% end %>
  
    <div class="links-wrapper">
      <h6 class="text-uppercase">Next</h6>
      <%= link_to "Add Available Dates", calendar_location_path(@location), class: "btn btn-primary" %>
    </div>
  </div>
</div>


<script type="text/javascript">
  // The following dropzone code has to be here. Getting error in the browser console 
  // when the code is initialized from the application.js folder.
  $(document).ready(function(){
    // disable auto discover
    Dropzone.autoDiscover = false;
 
    var dropzone = new Dropzone (".dropzone", {
      maxFilesize: 256, // Set the maximum file size to 256 MB
      paramName: "location[location_images_attributes][0][picture]", // Rails expects the file upload to be something like model[field_name]
      addRemoveLinks: false // Don't show remove links on dropzone itself.
    }); 
  });
</script>

app/views/locations/calendar.html.erb
<div class="container">
  <div class="dates-wrapper">
    <h2 class="main-title">Available Dates</h2>
    <%= form_tag({controller: "locations", action: "add_available_dates"}, method: "get", class: "form-inline") do %>
      <div class="form-group">
        <%= text_field_tag :start_date, nil, id: 'datepicker-start', class: "form-control", placeholder: "Start Date" %>
      </div>
      <div class="form-group">
        <%= text_field_tag :end_date, nil, id: 'datepicker-end', class: "form-control", placeholder: "End Date" %>
      </div>
      <%= submit_tag "Add available dates", class: "btn btn-primary" %>
    <% end %>
  </div>
  
  <h2 class="main-title"></h2>
  <div id="calendar" class="calendar-wrapper"></div>
</div>


<script type="text/javascript">
  $('#calendar').fullCalendar({
    events: '/locations/<%= @location.id %>/calendar.json'
  });
</script>

app/views/locations/edit.html.erb
<div class="container">
  <h2 class="main-title">Update Location</h2>
  
  <div class="items-form">
    <%= render 'form', location: @location %>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container locations-wrapper">
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Refine Your Search</h3>
        </div>
        <ul class="list-group">
        <%= form_tag locations_path, method: :get do %>
          <li class="list-group-item">
            <h5>Destination</h5>
            <div class="form-group">
              <%= text_field_tag(:address, nil, class: "form-control", placeholder: "where to? city, state, address") %>
            </div>
          </li>
          <li class="list-group-item">
            <h5>Travel Dates</h5>
            <div class="form-group"> 
              <%= text_field_tag(:start_date, nil, id: "datepicker-start", class: "form-control", placeholder: "check in") %>
            </div>
            <div class="form-group">
              <%= text_field_tag(:end_date, nil, id: "datepicker-end", class: "form-control", placeholder: "check out") %>
            </div>
          </li>
          <li class="list-group-item">
            <h5>Musical Instruments</h5>
            <div class="form-group">
              <%= select_tag "musical_instrument", "<option>Piano</option><option>Drums</option><option>Cello</option>".html_safe, prompt: "Select Musical Instrument" %>
            </div>
          </li>
          <li class="list-group-item">
            <h5>Guests</h5>
            <div class="form-group">
              <%= select_tag "guests", "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option>".html_safe, prompt: "Select Guests" %>
            </div>
          </li>
          <li class="list-group-item">
            <%= submit_tag "Find Properties", name: "commit", class: "btn btn-primary" %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-9">
      <% @locations.each do |location| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="row">
              <div class="col-md-5">
                <% unless location.location_images.empty? %>
                  <%= link_to( image_tag(location.location_images[0].picture.url(:square), class: "location-picture", alt: "location picture"), location ) %>
                <% end %>
              </div>
              <div class="col-md-7">
                <h2><%= link_to( location.title, location, class: "location-link" ) %></h2>
                <h5><em><%= location.address_1 %>, <%= location.city %></em></h5>
                <p class="text-wrapper"><%= location.description %></p>
                <h5 class="text-wrapper">Musical Instrument: <%= location.musical_instrument %></h5>
                <h6 class="text-uppercase"><%= location.guests %> guests</h6>
                <h6 class="text-uppercase"><%= number_to_currency(location.night_rate, unit: '€') %> / night</h6>
                <h5 class="text-capitalize location-link text-wrapper"><i class="fa fa-arrow-circle-right"></i><%= link_to("View this property", location, class: "location-link" ) %> <h5>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      
      <div class="pagination-wrapper">
        <%= link_to_previous_page @locations, '<i class="fa fa-chevron-left" aria-hidden="true"></i> Previous'.html_safe, class: "pagination-link btn btn-warning" %>
        <%= link_to_next_page @locations, 'Next <i class="fa fa-chevron-right" aria-hidden="true"></i>'.html_safe, class: "pagination-link btn btn-warning" %>
      </div>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="container">
  <h2 class="main-title">Your New Location</h2>
  
  <div class="items-form">
    <%= render 'form', location: @location %>
  </div>
  
</div>

app/views/locations/show.html.erb
<div class="container location-page">
  
  <section>
    <div class="row">
      <div class="col-md-6">
        <h1 class="text-uppercase"><%= @location.title %></h1>
      </div>

      <div class="col-md-6 pull-right">
        <div class="pull-right">
          <h5><%= @location.address_1 %></h5>
          <h5><%= @location.address_2 if @location.address_2 %></h5>
          <h5><%= @location.city if @location.city %></h5>
          <h5><%= @location.state if  @location.state %></h5>
          <h5><%= "#{@location.postcode}" if @location.postcode %></h5>
        </div>
        
      </div>
    </div>
  </section>
  
  <section>
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for Reservation.new, url: new_reservation_path, html: { method: :get, class: "form-inline" }  do |f| %>
          <%= f.hidden_field :location_id, value: @location.id %>
          <label class="text-uppercase dates-form">Travel Dates</label>       
          <div class="form-group">
            <%= f.text_field :start_date, id: "datepicker-start", class: "form-control", placeholder: "check in" %>
          </div>
          <div class="form-group">
            <%= f.text_field :end_date, id: "datepicker-end", class: "form-control", placeholder: "check out" %>
          </div>
          <%= f.submit "Reserve Location", class: "btn btn-warning pull-right" %>
          <span id="text-center" class="text-uppercase pull-right"><%= number_to_currency(@location.night_rate, unit: '€') %> per night</span>
        <% end %>
      </div>
    </div>
  </section>

  <section>
    <div class="fotorama" 
          data-auto="false" 
          data-nav="thumbs" 
          data-width="100%"
          data-ratio="4/3">
      <% @location.location_images.each do |image| %>
        <%= image_tag image.picture.url(:medium), class: "location-picture", alt: "location picture" %>
      <% end %>
    </div>
  </section>
  
  <section>
    <h3>Description:</h3>
    <p><%= @location.description %></p>
  </section>
  
  <section>
    <h5>Max guests</h5>
    <p><%= @location.guests %></p> 
  </section>
  
  <section>
    <h5>Musical instrument</h5>
    <p><%= @location.musical_instrument %></p>
  </section>

  <section id="profile">
    <div class="row">
      <div class="col-md-3">
        <%= image_tag @location.member.profile.avatar.url(:square), class: "profile-picture", alt: "profile picture" %>
      </div>
      <div class="col-md-9">
        <h3><%= @location.member.name %></h3>
        <h5><%= @location.member.profile.bio %></h5>
      </div>
    </div>
  </section>
</div>

 
<div class="container-fluid">
  <div id="map"></div>
</div>


<!-- SCRIPT for google maps and availableDates-->
<script type="text/javascript">
  google.maps.event.addDomListener(window, 'load', initMap(<%= @location.latitude || 0 %>, <%= @location.longitude || 0 %>));

  var availableDates = <%= @available_dates.to_s.html_safe %>
</script>