config/routes.rb
Rails.application.routes.draw do

  get 'reservations/new'

  devise_for  :members, 
              :path => '',
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'signup'},
              :controllers => { :registrations => 'registrations', 
                                :omniauth_callbacks => "omniauth_callbacks" }

  
  root 'home#index'

  resources :members, only: [:edit, :update] do
    resource :profile, only: [:edit, :update, :destroy] do
      collection do
        patch 'upload_avatar'
      end
    end
  end

  resources :members do
    get :payout_account, on: :member
  end
  
  resource :member, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  get 'profile', to: 'profiles#edit'
  get 'host_locations', to: 'members#member_locations'

  resources :locations do
    member do
      get :add_images
      get :calendar
      get :add_available_dates
    end
  end

  resources :reservations, only: [:new, :create, :index] do
    get :confirmation, on: :member
  end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:google_oauth2, :stripe_connect]

  has_one :profile
  has_many :locations
  has_many :reservations
  
  accepts_nested_attributes_for :profile, allow_destroy: true

  validates_presence_of :name

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |member|
      member.email = auth.info.email
      member.password = Devise.friendly_token[0,20]
      # add empty string in case there is no name from the provider
      member.name = auth.info.name || ""       
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_member!
  before_action :set_member, only: [:update, :update_password, :member_locations]

  def update 
    @profile = @member.profile
    # authorize a member with profile
    authorize @profile
    respond_to do |format|
      if @member.update(member_params)
        flash[:notice] = "Profile was updated successfully."
        format.html { redirect_to profile_path }
      else
        flash[:alert] = "Profile was not saved. #{@member.errors.full_messages.join(" ")}."
        format.html { redirect_to profile_path }
      end
    end
  end

  def update_password
    @profile = @member.profile
    authorize @profile
    if @member.update(member_params)
      # Sign in the member by passing validation in case their password changed
      bypass_sign_in(@member)
      redirect_to profile_path, notice: "Password was successfully changed."     
    else
      redirect_to profile_path, alert: "New password was not saved."
    end
  end

  def member_locations 
    @locations = @member.locations.includes(:location_images)
  end

  def payout_account
  end

  private
  # Use callbacks to share common constraints between actions.
  def set_member
    if current_member 
      @member = Member.find(current_member.id)
    else  
      @member = Member.find(params[:id])
    end
  end

  # Prevent params 
  def member_params
    params
      .require(:member)
      .permit(:name, :email, :password, profile_attributes: [:id, :bio])
  end
end

app/helpers/member_helper.rb
module MemberHelper
end

app/views/members/edit.html.erb
<div class="container">
  <div class="profile-wrapper">
    <h1 class="profile-title">Member edit page</h1>
  </div>
</div>

app/views/members/member_locations.html.erb
<div class="container locations-wrapper">
  <h2>Your's Hosted Locations</h2>

  <% if @locations.empty? %>
    <h4><em>You have no locations listed.</em></h4>
  <% else %>
    <% @locations.each do |location| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-md-5">
              <% unless location.location_images.empty? %>
                <%= link_to( image_tag(location.location_images[0].picture.url(:square), class: "location-picture", alt: "location picture"), location ) %>
              <% end %>
            </div>
            <div class="col-md-7">
              <h2><%= link_to( location.title, location, class: "location-link" ) %></h2>
              <h5><em><%= location.address_1 %>, <%= location.city %></em></h5>
              <p class="text-wrapper"><%= location.description %></p>
              <h5 class="text-wrapper">Musical Instrument: <%= location.musical_instrument %></h5>
              <h6 class="text-uppercase"><%= location.guests %> guests</h6>
              <h6 class="text-uppercase"><%= number_to_currency(location.night_rate, unit: '€') %> / night</h6>
              <h5 class="text-wrapper">
                <%= link_to 'View', location %> 
                <%= link_to 'Update', edit_location_path(location) %>
                <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' } %>
              </h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/members/payout_account.html.erb
<div>Get Paid with Stripe!</div>

<div>
  <%= link_to "Connect With Stripe", member_stripe_connect_omniauth_authorize_path %>
</div>